{% set version = "1.4.2" %}

package:
  name: cfncluster
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cfncluster/cfncluster-{{ version }}.tar.gz
  sha256: 64d47ccd6c5842385730a6e07047ca703edb232e8e75d65f470fcbd2b3beaf6e

build:
  number: 1002
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - cfncluster = cfncluster.cli:main

requirements:
  host:
    - python
    - pip
    - boto >=2.48.0
    - awscli >=1.11.175
    - future >=0.16.0
    - configparser  # [py2k]

  run:
    - python
    - boto >=2.48.0
    - awscli >=1.11.175
    - future >=0.16.0
    - configparser  # [py2k]
    - setuptools

test:
  imports:
    - cfncluster
  commands:
    - cfncluster --help

about:
  home: https://github.com/awslabs/cfncluster
  license: Apache
  license_file: LICENSE.txt
  license_family: APACHE
  summary: 'Management of HPC clusters on Amazon Web Services using CloudFormation'

  description: |
    CfnCluster (“cloud formation cluster”) is a framework that deploys and maintains high performance computing clusters on
    Amazon Web Services (AWS). Developed by AWS, CfnCluster facilitates both quick start proof of concepts (POCs) and
    production deployments. CfnCluster supports many different types of clustered applications and can easily be extended to
    support different frameworks. Download CfnCluster today to see how CfnCluster’s command line interface leverages AWS
    CloudFormation templates and other AWS cloud services.
  doc_url: http://cfncluster.readthedocs.io/en/latest/
  dev_url: https://github.com/awslabs/cfncluster

extra:
  recipe-maintainers:
    - notestaff
