travis:
  secure:
    BINSTAR_TOKEN: Q0BgTOWcrglbPZlS1qHeMGivGhF8wX2qsXCy2M7c48DZ5AZUxeiaRlAj/QpRm8+VfL93ix680SVsIyjiAyYFMO8msH2N4Gek7Zo9nsIurf9f2sLtBDXP3QgKqUnGKR47qLbPzURLgkxUCaY2lZv6TEzW/5vPcD7a5VrDG133V7tN6feR/vOqVqAd+6qAL2WEiClLmkrZJwEs1/AaimfjnV5u2AcT56No4FJt+KM5uFpUpndq52lbznxcxI3lM9stubEBJRisQWui1X1GsEkqo88lHj9qamtQLruDg0J6/20+VUNxdL3xikCJAKbOe06oKd1MErIgFe4MnvJo6CCkZiyrhU3IlWSmrPa0lUFse5vgEf0NLiUhCiCQt2UtOB/Ek0nDrcE7efLgwPiv6v/ggaZZqtG54RxAaBO69PtaK/RmKgDk9eiaIWiqe127dxll8BEz40TA289rKTZCekXqMzUCpLznATlmAfknbPXEY6mcyaSz9A+bWzx+lTw3uglF8E6/xD4Ts9ZrH8nsUKUfp8Rd1gnMFpDEE4RtCLFFbvkZOfmXnVoQeNAUPSo72rpOi7BE8orrFrDbCR7K2dcHqbkQQCjhfh5YJNaUkvQhm5ckgi+VcyBPc2ARNtW3GWjsBNX3oG8VQ0XlkJbgoCUtWd0hzugKBuy1/n+TR6ZkRaU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
