travis:
  secure:
    BINSTAR_TOKEN: RLEOJE/NbCkB3GOuThsZY7+Rg+TNWkCaomuJy3cMyFe0hKGQbktTNM3G8VahC+1sW3uoKf9UwRr9oSaLra7Cny769UTUSy9eFMU48q/LyOffdP0k/lQUrOZfKa4WEaUXLHXhms504Cq1qzrTuTXNsAPsgbyOI3T8FNaG3QRCKQI7sTDUFky5mQygqH618YPAE9Xv5UW2BrLAFdlvdakGuwyKY8jEC2nok0b96H4tg4fpXKnZwubwl1NACE187UdAiXRW4+EDcdunxmwwn6J/rDaUmSlYkIjm5vEnA0FyghT4xdU+3u/PsMPvzzRIf4z/NM3HQ0G5W5CkBjd15zFAeKjbrzUBpJfh7A+bJVFlp2qopBKpAHSiL4W3aThKoWF+4BSO6n7PRdFpeWVLu/mQBV6DAA07dNLaTyS4SDGV9RnPYnEAWNj09/K/e9NLcC/XMOfxOjpu3/s/FMR9p67BgOnKDFGUmU0MGa95ZtiyJt/YndLJXUPyzUmCQx31+FPR0U2y9DdaOJJ/73sZv09EflRz/pZpeivdl+MHqM+A1QBNeJfnXgxQqtzJIWGe/mZCglE7Wv3loMf6DMsyVCqDavaOipgOmV+s0ahu0lj7E+a31YTDJScSoYmYdj51DlC2VSpq5TxW7wW83Z5dSOedClaJojURWtTACcjFasR2mx0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
