travis:
  secure:
    BINSTAR_TOKEN: KwA3DhygzfneFtTr9450FhbFWiyBHtz42mFQrW8dzcN44EHqFS4w7gkp6iXEx1AM9zO+pIYpeufPzfbQlMKRwgYsg0o50FAlqqETvDmCqPcoYipOyyLtiSQWgKmXIZ83wqrt6k2TdVKFYu+/QfbMO2ankoUgGU0Y0BuYoF+ZKb3qHhFBIx7g7Hc7oxzKcsKN+n3eeYN+9v6Hws553lYwii1Uz8LgOR5ZM0/pAdcNLk52dPsHzL+FAlVpV5noJXbLW8P9Oqr5Cudfqk1f5o4plAiIk4X8l5G8+UwcQzDrqWCzOyP8jL5XCXEp0LgWL48ug1n/z1yNJsV0yaj4TV7HX5Ze59G2/6JScmdIsoTMy7gljb8fsy3elF2/oJqYg+cUQ3Umrcg4nCjO4QSiIjSpfHqCWKm5V5EUKjIK61lMpjn6TN20u7G1vDyNjOq0p9Duk4iFuf+w86NiDN/K6Mm8VCdwBfFyvQaKLzkORaqYD7hA2z8oB+8cxKuN0wU+62FLRsiYag7ri174ByaezyE1hUzAr8PoMocLIIGrUazhIyj3qnEKKQz3CDFZuKg0Rn3C4Z5Mh9yk/XWHQJStoJqNd6R1sMB+1y9lADb4bhB+Lwso31UpjIhBVZgiLzCkx06Y5YKbCMRwbbkd9E2U/FrIpJjZyo8+IfzzTgV39dhg01I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
